gleam-lang/stdlib

- gen/src/gleam@dynamic.erl
- gen/test/gleam@dynamic_test.erl
- src/gleam/dynamic.gleam
- src/gleam_stdlib.erl
- test/gleam/dynamic_test.gleam
Hello!
I was writing some Gleam bindings to an Erlang library and realized that I wanted to be able to decode a tuple, but couldn't (or at least couldn't figure out how to) with existing decoding functions in `gleam/dynamic`.
This adds a new function to the `dynamic` module, called `element` in the spirit of the other decoding function names (e.g. `field`), which takes a `from: Dynamic` (which is hopefully a tuple!) and a `position: Int`, and returns a result with either the element from that tuple at that position (if it is in bounds), or an error with a helpful message.
Any feedback appreciated!
> Add dynamic.element for decoding tuples

- rebar.config
- src/gleam_stdlib.erl
I pulled the `master` branch into my project to use `dynamic.element` and noticed this warning:
```
===> Compiling gleam_stdlib
_build/default/lib/gleam_stdlib/src/gleam_stdlib.erl:81: Warning: variable 'Position' is unused
```
This should fix it!
> Add leading underscore to unused Erlang arg

- CHANGELOG.md
- gen/src/gleam@string.erl
- gen/test/gleam@int_test.erl
- gen/test/gleam@string_test.erl
- src/gleam/string.gleam
- src/gleam_stdlib.erl
- test/gleam/string_test.gleam
Given the fact that I am still getting my feet wet with both Erlang and Gleam I made this small addition.
Feedback is welcome so that I can start adding more.
I am assuming that:
- Gleam models its stdlib somewhat after Elm
- Mapping to Erlang stdlib is generally preferable above a pure Gleam implementation for performance reasons
> string.trim

- CHANGELOG.md
- src/gleam/result.gleam
- test/gleam/result_test.gleam
I find you might have to use map_error a lot and I thought this function might be useful.
> Add nil_error function

- CHANGELOG.md
- src/gleam/string.gleam
- test/gleam/string_test.gleam
Adds `string.to_graphemes`.
I am assuming we want this to be in Gleam based on `string.pop_grapheme`.
> string.to_graphemes

- CHANGELOG.md
- src/gleam/binary.gleam
- src/gleam/binary_native.erl
- test/gleam/binary_test.gleam
Module defining binary types and a few operations,
Even though there is no syntax to define a binary this is useful as the correct type to return in a variety of places. My personal usecase include hashing base32 encoding and reading from TCP sockets
> Add a binary module

- CHANGELOG.md
- src/gleam/regex.gleam
- src/gleam_stdlib.erl
- test/gleam/regex_test.gleam
Added `Regex` module.
It's mostly modeled after: https://package.elm-lang.org/packages/elm/regex/latest/Regex
This only enables you to create regular expressions from strings and match against them.
Additional functionality will be in subsequent PRs.
> Regex module

- CHANGELOG.md
- src/gleam/base.gleam
- src/gleam_stdlib.erl
- test/gleam/base_test.gleam
This PR just adds base64 and url version of encoding. This is because:
-  erlang stdlibrary has support for it https://erlang.org/doc/man/base64.html
- it is useful on it's own, i.e. in basic authentication headers
> Add Base module

- CHANGELOG.md
- src/gleam/float.gleam
- test/gleam/float_test.gleam
This PR attempts to address some of what was discussed in #100 aimed at the float module.
This PR adds the following functions to the float module:
- `absolute_value`
- `square_root`
- `power`
In terms of implementation, `abs` is available as a BIF in erlang, so I am just making an external call to that. The square root and power functions were also simple enough that I thought it would be fine to make these external calls to the erlang stdlib as well.
Please let me know any thoughts/criticisms/opinions regarding this.
> Add a few simple math functions to the float module

- src/gleam/bit_string.gleam
Wasn't sure that it was worth adding this to the CHANGELOG, but happy to do so if we'd like.
> Fix typo in `bit_string.to_string` doc

- CHANGELOG.md
- src/gleam/result.gleam
- test/gleam/result_test.gleam
Add a function to combine a list of results into a single result.
Doesn't seem to have a common name: `sequence` in haskell. `Result.Extra.combine` in Elm. `Result.all` in OCaml Base
This is a function I use from time to time. I think it could be a good addition.
> Add result.all

- CHANGELOG.md
- src/gleam/uri.gleam
- test/gleam/uri_test.gleam
https://github.com/gleam-lang/stdlib/issues/118
Add functions to encode and decode a url component.
Unsure about the naming, this goes by many names in different languages. `percent_encode` seems to tell very clearly what this is about.
I tried to find a function in erlang that would this but couldn't.
There is `http_uri.encode`. But this module is deprecated apparently. And is not consitent with `query_to_string` that is already in the std lib.
There is `uri_string.transcode`. But I couldn't figure out how to get the results. Tried a bunch of in and out encoding, but nothing.
I ended up using the functions `query_to_string` and `parse_query` already in the module. This ensures consistency.
This behaves a bit different than the JS implementation. e.g. in JS (encodeURIComponent spaces …
> Add percent_encode and percent_decode

- CHANGELOG.md
- src/gleam/iterator.gleam
- test/gleam/iterator_test.gleam
The following functions are added to iterator:
* append
* flatten
* flat_map
I was unsure about the naming for `append`. I decided to use `append` given the existing `string.append` function, but I also felt that `concat` could be appropriate.
> Add flat_map and friends to iterator

- CHANGELOG.md
- src/gleam/iterator.gleam
- test/gleam/iterator_test.gleam
The `step` function allows eager access to the first item in the iterator, but does not force the rest of the iterator.
> Add `step` eliminator for iterators

- CHANGELOG.md
- src/gleam/float.gleam
- src/gleam/int.gleam
- test/gleam/float_test.gleam
- test/gleam/int_test.gleam
Piggybacking off of @lrosa007's work with the sum function and discussion in the discord to add a respective product function for the `Int` and `Float` modules.
> Add product function to int and float modules

- CHANGELOG.md
- src/gleam/int.gleam
- test/gleam/int_test.gleam
`float` has `absolute_value` but `int` doesn't.
Add `int.absolute_value`.
Unsure if the erlang implementation is better somehow, but this seems pretty straighforward in plain Gleam.
> Add int.absolute_value

- CHANGELOG.md
- src/gleam/queue.gleam
- test/gleam/queue_test.gleam
Solve https://github.com/gleam-lang/stdlib/issues/147
- Change `from_list` so the head of the list is the front of the queue
- Fix `pop_back` and `pop_front` to do the correct behaviour
> Change queue.from_list. Fix queue.pop_back and queue.pop_front

- CHANGELOG.md
- src/gleam/result.gleam
- test/gleam/result_test.gleam
As discussed in https://github.com/gleam-lang/stdlib/issues/153
This adds `result.replace_error`
> Add result.replace_error

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
As discussed in https://github.com/gleam-lang/stdlib/issues/153
Adds list.index_fold and list.try_fold
> list.index_fold and list.try_fold

- test/gleam/atom_test.gleam
`atom_test.from_string_test/0` uses `ok` to test `atom.from_string/0`. However,
the availability of the `ok` atom seems to be a side effect of running the test
trough eunit.
This patch explicitly creates an atom to make sure it exists before using it to
test `atom.from_string/1`. It removes the assertion on `expect`, which had the
same issue and doesn't seem to test another case.
> Ensure atom exists before atom from_string_test

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
As discussed in https://github.com/gleam-lang/stdlib/issues/153
This adds two functions to list.
`windows` is a generic sliding windows, where you can pass the number of items desired.
`window2` is a special version that returns a `List(tuple(a,a))`. This has the advantage that the elements in the list are of a known size, so is more convenient for when you only need two. Maybe this could be named `windows_of_2`.
> Add list.window and list.window_by_2

- src/gleam/io.gleam
- src/gleam_stdlib.erl
Adds a `get_line` function to the io module.
I couldn't figure out a way to represent the payload of the "rare" NoData error conditions returned by `io:get_line` so I've simply ignored it.
> Add io.get_line function

- src/gleam/atom.gleam
- src/gleam/bit_builder.gleam
- src/gleam/bit_string.gleam
- src/gleam/dynamic.gleam
- src/gleam/float.gleam
- src/gleam/int.gleam
- src/gleam/io.gleam
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/map.gleam
- src/gleam/option.gleam
- src/gleam/os.gleam
- src/gleam/queue.gleam
- src/gleam/regex.gleam
- src/gleam/result.gleam
- src/gleam/set.gleam
- src/gleam/string.gleam
- src/gleam/string_builder.gleam
- src/gleam/uri.gleam
This PR updates the function docs to use a consistent phrasing.
* `Return` -> `Returns`
* `Check` -> `Checks`
* `Convert` -> `Convertst`
* ...
> Use consistent phrasing in function docs

- CHANGELOG.md
- src/gleam/dynamic.gleam
- src/gleam_stdlib.erl
- test/gleam/dynamic_test.gleam
Fixes #92.
Implements `dynamic.typed_tuple{3,4,5,6}` and `dynamic.tuple{3,4,5,6}`.
> Add dynamic.tuple{3,4,5,6} 

- src/gleam/list.gleam
- test/gleam/list_test.gleam
Changed the implementation to accumulate tail recursively and then reverse the result, not sure if there's a better solution...
I also modified the test case to show that any elements that fulfill the predicate after the first failed one are skipped as well.
Closes #167
> Make list.take_while tail recursive

- src/gleam/iterator.gleam
- test/gleam/iterator_test.gleam
Adds `iterator.index`, which is similar to `list.index_map`, or Rust's `Iterator::enumerate`
> Add iterator.index

- src/gleam/iterator.gleam
- test/gleam/iterator_test.gleam
Adds `scan`, an iterator that acts like `fold`, but yields intermediate results.
> Add iterator.scan

- src/gleam/uri.gleam
- test/gleam/uri_test.gleam
This fixes https://github.com/gleam-lang/stdlib/issues/164 and adds more examples to uri
> Add Examples to uri

- README.md
I was trying out gleam, and these instructions and examples would have made it a bit easier to get up and running
> Add installation instructions and usage examples to the README

- CHANGELOG.md
- src/gleam/iterator.gleam
- src/gleam/string.gleam
- test/gleam/iterator_test.gleam
Changes the behaviour of `iterator.take` to return an iterator that bounds another iterator up to a given number of elements.
Closes #179
> Make iterator.take return an iterator

- CHANGELOG.md
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- test/gleam/iterator_test.gleam
- test/gleam/list_test.gleam
Adds a direct equivalent of Elixir's `Stream.chunk_by` and `Stream.chunk_every/2`
> Add chunk functions for lists and iterators

- src/gleam/iterator.gleam
Highlights:
- In some helpers, like `do_drop` returning `Action` instead of `fn() -> Action` makes the code more readable
- ~~`do_flatten` used `do_append`, which is a tight coupling, and the resulting code wasn't very clean to read~~
- `cycle` can be represented as `repeat(iterator) |> flatten`
- `range` can be represented with `unfold`
- `find` didn't use a helper function, despite having a non-trivial implementation
- Corrected language in some doc comments
> Refactor the iterator module

- CHANGELOG.md
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- test/gleam/iterator_test.gleam
- Add iterator.{any, all}
- Simplify list.{any, all}
> `any`, `all` for lists and iterators

- src/gleam/iterator.gleam
- test/gleam/iterator_test.gleam
Adds a function to combine an iterator into a map of groups of elements that correspond to the same key
> Add iterator.group

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
As discussed in Discord, this function is quite useful when you want to map and pass a memo around.
> Add list map_reduce

- CHANGELOG.md
- src/gleam/string.gleam
- test/gleam/string_test.gleam
Wasn't completely sure about the labels for this function (not against modifying them if there are better suggestions), settled on: 
```rust
fn drop_before(from string: String, before substring: String) -> String
```
> add string.crop

- CHANGELOG.md
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- test/gleam/iterator_test.gleam
- test/gleam/list_test.gleam
Add a convenience function for cases when you want to fold a list/iterator on its first element.
The name is taken from Rust, might be mistaken with the recently added `map_reduce`, but I can't think of a good alternative...
> Add {iterator, list}.reduce

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
I noticed `iterator` had a `scan` function but `list` didn't.
> add list.scan

- src/gleam/result.gleam
Fix typo in `lazy_unwrap` documentation
> fix typo in `lazy_unwrap` docs

- .github/workflows/ci.yml
- CHANGELOG.md
- src/gleam/dynamic.gleam
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/map.gleam
- src/gleam/option.gleam
- src/gleam/os.gleam
- src/gleam/pair.gleam
- src/gleam/queue.gleam
- src/gleam/result.gleam
- src/gleam/set.gleam
- src/gleam/string.gleam
- src/gleam/uri.gleam
- test/gleam/dynamic_test.gleam
- test/gleam/function_test.gleam
- test/gleam/iterator_test.gleam
- test/gleam/list_test.gleam
- test/gleam/map_test.gleam
- test/gleam/os_test.gleam
- test/gleam/pair_test.gleam
- test/gleam/result_test.gleam
- test/gleam/string_test.gleam
- test/gleam/uri_test.gleam
Makes stdlib use new tuples and switches CI so that it tests with Gleam 0.15.0
> Reformat to new tuple syntax

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
`iterator` has `flat_map`. But with list you need to do `map` and then `flatten`.
It would be great to have `list.flat_map` as well.
> Add list.flat_map

- CHANGELOG.md
- src/gleam/os.gleam
- test/gleam/os_test.gleam
Closes #206 (hopefully)
Replaces string ↔️ char list functions with their unicode counterparts.
Adds a unit test (source: https://marekj.github.io/2013/07/09/unicode-for-testers)
> Support unicode in env variables

- src/gleam/list.gleam
Every fold in list has a named argument `over`. Except `fold_right`.
Add this named argument for consistency.
> Add "over" named arg for fold_right

- .gitignore
Useful when testing with gleam compiled from the main branch
> Ignore local asdf config file

- CHANGELOG.md
- src/gleam/base.gleam
- src/gleam/bit_builder.gleam
- src/gleam/bit_string.gleam
- src/gleam/bool.gleam
- src/gleam/dynamic.gleam
- src/gleam/float.gleam
- src/gleam/int.gleam
- src/gleam/list.gleam
- src/gleam/result.gleam
- src/gleam/string.gleam
- test/gleam/base_test.gleam
Cleans up stdlib since we now have importable prelude
> Remove redefinitions of types from the prelude

- src/gleam/bool.gleam
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/option.gleam
- src/gleam/pair.gleam
- src/gleam/queue.gleam
- src/gleam/result.gleam
- src/gleam/string_builder.gleam
Found with a hacky little doc-test script.
This node script generates an ugly little test file with some of the doc tests:
```javascript
import * as fs from "fs";
const doctextRegex = /\/\/\/    > ([^\n]*)\n\/\/\/    ([^>].*)\n/gm;
function main(args) {
const file = args[1];
const contents = fs.readFileSync(file, "utf8");
const matches = contents.matchAll(doctextRegex);
const testBlocks = [];
let index = 1;
for (const entry of matches) {
testBlocks.push(`pub fn doc_${index}_test() {
${entry[1]}
|> should.equal(${entry[2]})
}`);
index++;
}
const output = `
import gleam/should
import gleam/order
import gleam/bool.{to_int, negate, nor, nand, exclusive_or, exclusive_nor, compare, max, min}
${testBlocks.join("\n")}
`;
fs.writeFileSync("test/gleam/doc_test.gleam", output);
} …
```
> Correct function in doc tests

- src/gleam/float.gleam
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/option.gleam
- src/gleam/result.gleam
I'm not sure how you feel about removing the parameter names. The compiler output errors when running as erlang tests so it seems necessary but maybe there are other approaches.
> Further doc test fixes

- CHANGELOG.md
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- test/gleam/iterator_test.gleam
noticed this was in `list` but not `iterator`
> iterator.try_fold

- CHANGELOG.md
- src/gleam/dynamic.gleam
- src/gleam_stdlib.erl
- test/gleam/dynamic_test.gleam
Instead of returning a string we return a structured error.
We update all the call sites and tests and then update the
implementation of 'decode_int', 'decode_error_msg' and 'classify' as an
example of how it might go for the rest of them.
For gleam-lang/gleam#1226
---
Does this seem like it is going in the right direction or have I misunderstood something? My knowledge of erlang is still practically zero unfortunately.
> Improve dynamic decoding error

- src/gleam/result.gleam
Hi,
As the title says, this PR fixes examples in `result.lazy_or` docs.
> Fix examples in `result.lazy_or` docs

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
Previously indices < 0 resulted in `Error`, now are normalized to 0, for consistence with `iterator`.
> Simplify and unify `list.at` with `iterator.at`

- src/gleam/list.gleam
The arguments in this example are mislabeled
(Thanks for all your work! I'm trying out Gleam for advent of code and loving it.)
> Update `index_fold` doc example

- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/map.gleam
- test/gleam/iterator_test.gleam
- test/gleam/list_test.gleam
Closes #245
This is a superset of #246. This corrects all mentions I could find of the accumulator being in the incorrect argument position in the documentation and updates it to the correct position.
> Correct accumulator argument position in documentation

- src/gleam/map.gleam
At least I _believe_ the old code example is not a valid syntax.
> Fix forgotten comma in map.update documentation

- src/gleam/string.gleam
the `to_option("")` example was repeated twice, I figured it was a mistake. Other examples use the word hats so I added it here too.
> docs: improve string.to_option example

- src/gleam/bit_builder.gleam
- src/gleam/string_builder.gleam
Does what it says on the tin, really. Some people might prefer to construct builders starting from "nothing", so:
```
new()
|> append(foo_builder)
|> append(bar_builder)
```
instead of:
```
foo_builder
|> append(bar_builder)
```
> ✨ Add `new` constructor functions for empty `BitBuilder`s and `StringBuilder`s.

- CHANGELOG.md
- src/gleam/bool.gleam
- test/gleam/bool_test.gleam
Debated on having the string be lowercase, or having a separate `to_json_string` method as well, but it's not too hard to just `string.lowercase(bool.to_string(x))`, so this is probably enough?
> Add `to_string` method to bool.gleam

- test/gleam/function_test.gleam
Cleans up test https://github.com/gleam-lang/stdlib/pull/282
The test was pushing data to stdout.
`gleam test` did not show io.print but `gleam test --target javascript` would.
> tidy function.tap_test

- CHANGELOG.md
- src/gleam_stdlib.mjs
Fixes this on nodejs v14, the error did not occur on nodejs v16 or v17 as replaceAll is implemented there natively:
```
❯ nvm use 14
Now using node v14.17.0 (npm v8.5.3)
❯ gleam test --target javascript
Compiling gleam_stdlib
Compiled in 0.57s
Running gleam_stdlib_test.main
Running tests...
................
❌ 
gleam/string_test..replace_test: TypeError: Cannot use 'in' operator to search for 'replaceAll' in Gleam,Erlang,Elixir
❌ 
gleam/base_test..encode64_test: TypeError: Cannot use 'in' operator to search for 'replaceAll' in /3/+/A==
❌ 
gleam/base_test..url_decode64_test: TypeError: Cannot use 'in' operator to search for 'replaceAll' in _3_-_A==
❌ 
gleam/base_test..url_encode64_test: TypeError: Cannot use 'in' operator to search for 'replaceAll' in /3/+/A==
........................... …
```
> fix unit test failing over missing string.replaceAll() implementation on nodejs <= 14

- README.md
- src/gleam/dynamic.gleam
- src/gleam/int.gleam
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/map.gleam
- src/gleam/set.gleam
- src/gleam/string.gleam
- src/gleam/uri.gleam
- test/gleam/bit_builder_test.gleam
- test/gleam/dynamic_test.gleam
- test/gleam/float_test.gleam
- test/gleam/function_test.gleam
- test/gleam/int_test.gleam
- test/gleam/iterator_test.gleam
- test/gleam/list_test.gleam
- test/gleam/map_test.gleam
- test/gleam/option_test.gleam
- test/gleam/order_test.gleam
- test/gleam/pair_test.gleam
- test/gleam/queue_test.gleam
- test/gleam/regex_test.gleam
- test/gleam/result_test.gleam
- test/gleam/set_test.gleam
- test/gleam/string_test.gleam
- test/gleam/uri_test.gleam
- fix docs typo
- fix test missleading/inconsistent variable naming (of prev own PR)
- sort all imports
- remove useless docs trailing whitespaces
> Nitpickery

- src/gleam/list.gleam
The example for `map_fold` does not match the types.
I'm very new to Gleam so please ignore if I got it wrong :)
> Fix map_fold example

- CHANGELOG.md
- src/gleam/string.gleam
- test/gleam/string_test.gleam
As a part of my Gleam learning process, I've been reading through the standard library, and I noticed that it is currently missing a few `String` functions that are provided by Elixir (or at least so it seems to my untrained eye). I've used the documentation [here](https://hexdocs.pm/elixir/String.html#functions) as a reference for the implementations.
Please, let me know if these functions are not deemed useful, or if I've overlooked anything.
> Add functions to `String`

- test/gleam/string_test.gleam
atm just shows failing test
Edit: for the failing JS test see https://github.com/gleam-lang/stdlib/pull/310
> String.inspect bitstring tests

- CHANGELOG.md
- src/gleam_stdlib.mjs
- test/gleam/dynamic_test.gleam
Previously would fail, as JS arrays are recognized by `gleam/dynamic` as tuples.
> Let `decode_list` succeed with arrays

- src/gleam/list.gleam
- add missing docblock to `list.parition`
- add `gleam` prefixes to markdown code blocks in `///` docblocks
- move helper functions below public functions
- move function specific types below public functions
> list: fix missing dockblock, docblock markdown

- .github/workflows/ci.yml
- CHANGELOG.md
- src/gleam/dynamic.gleam
- src/gleam_stdlib.erl
closes #332
and thus closes https://github.com/gleam-lang/gleam/issues/1721
Let me know if you prefer to have a general function that just converts listish (list+improper list) to list - that fn could be reused, but then mapping in this case takes two recursion passes.
~~I am also not sure if my solution is TCO compatible.~~
> fix inspect on improper lists

- CHANGELOG.md
- src/gleam/int.gleam
- src/gleam/map.gleam
- test/gleam/int_test.gleam
As a side effect we have noticed the 0-safe stdlib functions were missing when @tynanbe discovered this bug https://github.com/gleam-lang/gleam/issues/1784
We were unsure if modulo and remainder are the same until I did some digging: <https://torstencurdt.com/tech/posts/modulo-of-negative-numbers/>
IMHO, we should make sure to call `%` ***remainder operator*** in gleam compiler code and any current and future gleam docs as it maps to C/Erlang behavior where it is also called remainder (and not modulo AFAIK).
I have also ported Elixir's `Integer.modulo` because that behavior for integer modulo/remainder division is also common in many languages (see link above).
> Add `int.{remainder, modulo}`

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
A tail recursive merge sort so that it doesn't blow up the call stack (especially in JS). See the code comments for a brief explanation of the algorithm, hopefully it makes sense!
Also thanks to @inoas for all the benchmarking.
> make list.sort tail recursive

- src/gleam/list.gleam
When reviewing my changes to `list.permutations` @schurhammer notices that `list.flatten` should lose the `append`. He suggested a reveres prepend for each list of lists.
AFAIU current implementation:
- walk the whole list to append
- walk the whole list + 1 to append next
- walk the whole list + 2 to append
- ...
- walk the whole list + n to append
How this PR works:
- Say we have `[[1,2], [3,4], [5,6]]`
- we take `[1,2]` and reverse prepend it into the accumulator `[]` to get `[2,1]`
- then take `[3, 4]` and reverse preprend it into `[2,1]` to get `[4,3,2,1]`
- and then `[5, 6]` and reverse and prepend to get `[6,5,4,3,2,1]`
- in the end the result`[6,5,4,3,2,1]` needs to be reversed again.
- In conclusion we have to walk each element once to reverse-prepend and then another time to …
> improve list.flatten speed in most cases

- CHANGELOG.md
- src/gleam_stdlib.erl
- test/gleam/regex_test.gleam
Closes: https://github.com/gleam-lang/stdlib/issues/356
> Regex use ucp flag because they use unicode flag

- src/gleam/string.gleam
This was introduced to benefit tail call optimization #338, but I don't think the intention was to allow users to use this function (all other `do_*` functions are private).
It also shows up in the [API docs](https://hexdocs.pm/gleam_stdlib/gleam/string.html#do_to_graphemes).
> Unpublish do_to_graphemes

- CHANGELOG.md
- src/gleam/bool.gleam
- src/gleam/float.gleam
- src/gleam/int.gleam
- test/gleam/bool_test.gleam
- test/gleam/float_test.gleam
- test/gleam/int_test.gleam
Allows using operators as functions. Useful in higher order functions or pipes.
See: #366
> Add operator functions

- src/gleam/bool.gleam
- src/gleam/dynamic.gleam
- src/gleam/float.gleam
- src/gleam/function.gleam
- src/gleam/int.gleam
- src/gleam/io.gleam
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/map.gleam
- src/gleam/option.gleam
- src/gleam/order.gleam
- src/gleam/queue.gleam
- src/gleam/regex.gleam
- src/gleam/result.gleam
- src/gleam/set.gleam
- src/gleam/string.gleam
- src/gleam/string_builder.gleam
- src/gleam/uri.gleam
- add missing gleam markdown prefixes.
- add newlines around Example headers and below source code blocks in docblocks.
- remove trailing line spaces
- remove unnecessary leading spaces
- remove double empty lines
- split multiple examples into multiple `'''gleam` blocks. ~~merge multiple Example blocks into one as that's the majorily common pattern.~~
- do not specify the module name you are in for docblocks
- add some missing imports of references modules/functions
> Format docblocks

- src/gleam_stdlib.erl
While editing `function.curry2` I've realized it speaks of arity and I have looked where else stdlib talks about arity and the only other place was `decode_thunk`.
I don't know what `decode_thunk` had been used for but it seems it is not being used anymore, is it?
If it still is removed I'd rephrase `zero arity function` to `function with 0 arguments`?
> Remove erlang ffi `decode_thunk` as it seems to be used nowhere

- CHANGELOG.md
- src/gleam_stdlib.mjs
Following discussion on Discord. This only applies to the Firefox, which fails the Intl.Segmenter
> JS/Firefox: also match newlines in string.length and string.pop_grapheme

- CHANGELOG.md
- src/gleam/iterator.gleam
- test/gleam/iterator_test.gleam
Rationale: this is a piece of missing surface in the public API to create various types of iterators without making `Iterator` itself public.
Notably, `map`, `take`, `take_while`, `index`, `scan`, can be fully written entirely using `transform` and `Step`.
todo:
> Add iterator.transform()

- CHANGELOG.md
- src/gleam/bit_string.gleam
- src/gleam_stdlib.erl
- test/gleam/bit_string_test.gleam
- test/gleam/dynamic_test.gleam
- test/gleam/string_test.gleam
Fixes https://github.com/gleam-lang/stdlib/issues/395
~~Tests do not pass on JS but it _seems_ to me that that issue has to be fixed in `gleam-lang/gleam`'s JS perlude?~~
Edit: fixed the tests, JS passes, Erlang fails.
> Fix `string.inspect` / `io.debug` escaping of `"`, `\`, `\n`, `\r`, `\r\n` and `\t`.

- src/gleam/dynamic.gleam
- src/gleam/map.gleam
- src/gleam/uri.gleam
Fixing some inaccurate examples in function documentation. This includes:
- `map.values`
- `dynamic.decode8`
- `dynamic.decode9`
- `uri.to_string`
> Fix Inaccurate Examples in Function Documentation

- CHANGELOG.md
- src/gleam/set.gleam
- test/gleam/set_test.gleam
Made to look as similar as possible to `map.drop`
I have used the same implementation in my project in several places for example
- https://github.com/midas-framework/project_wisdom/blob/cleanup/eyg/src/eyg/analysis/unification.gleam#L19
> Add set drop functionality

- CHANGELOG.md
- src/gleam_stdlib.mjs
Currently when using Deno `print`, `print_error`, and `print_debug` will default to `console.log`. This change makes the functions behave as they do on Node.
> fix: deno print to match node implementation

- CHANGELOG.md
- src/gleam/int.gleam
- test/gleam/int_test.gleam
`int.floor_divide(-1, by: 2)` currently returns `0`, instead of `-1`. I added a test case and basically copied what Elixir's [`Integer.floor_div/2`](https://github.com/elixir-lang/elixir/blob/v1.14.3/lib/elixir/lib/integer.ex#L163) does to fix the issue.
> Fix edge-case in int.floor_divide

- src/gleam/dynamic.gleam
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/string.gleam
- test/gleam/iterator_test.gleam
- test/gleam/list_test.gleam
- test/gleam/queue_test.gleam
- test/gleam/regex_test.gleam
- test/gleam/string_test.gleam
- test/gleam/uri_test.gleam
Also covers https://github.com/gleam-lang/stdlib/pull/416 (just because it was easier to run gleam fix/format and apply the one manual change)
> 0.27 gleam fix && gleam format, replace some asserts with panics in tests

- CHANGELOG.md
- src/gleam/iterator.gleam
- test/gleam/iterator_test.gleam
This PR adds `length` to the iterator module and resolves #382, thanks!
> Feature: Add `length` to the iterator module

- src/gleam/int.gleam
The doc comment for `int.to_base36` says "Prints a given int to a string using base16."
Change 16 to 36.
I also updated the language in the comments to say base-2, base-8, base-16, base-36 instead of base2, base8, base16, base36 which looked unnatural to read to me. English is not my first language so I might be off base here and I can revert that commit if so. A quick look at Wikipedia (for binary, octal, hexadecimal etc. numbers) shows me examples with hyphens or spaces. Base36 is written like that on Wikipedia, but it looks like that is because the article is about an encoding with that name.
> Fix `gleam/int.to_base36` doc comment

- src/gleam/regex.gleam
Sorry, One of the examples had an issue. I missed a `-` sign!
> minor fix for one of `regex.scan`'s examples

- src/persistent-hash-map.mjs
@CrowdHailer was having weird issues with the map, and I believe this is it.
There was a missing check for key equality when finding values in specific cases.
> fix bug in persistent-hash-map.mjs

- src/gleam/dynamic.gleam
As reported in #444 there were a couple of inconsistencies between the documentation examples and the actual return values of the `Decoder`s. I ended up finding more errors than those reported in the issue and fixed all of them.
Closes #444
> `dynamic` doc fixes

- CHANGELOG.md
- src/gleam/dynamic.gleam
- src/gleam_stdlib.erl
- src/gleam_stdlib.mjs
- test/gleam/dynamic_test.gleam
- Add an implementation for `optional_field` (closes #437)
- Fix an [inconsistency](https://discord.com/channels/768594524158427167/1098317468851777566) with the `field` behavior and its documentation. Now the standard behavior is the following:
- Erlang: if the dynamic is not a map it now states it in the error message, for example `1 |> dynamic.from |> dynamic.field("ok", dynamic.int)` now gives the more appropriate error `DecodeError(expected: Map, got: Int, path: [])` instead of `DecodeError(expected: field, found: nothing, path: [<field-name>])`. This error can only occur if the type is indeed a map but the field is missing
- Javascript: the behavior is a little more nuanced in case the field is missing:
- if the dynamic was a `PMap`, `Map`, `WeakMap` or plain object it will give an …
> `field` and `optional_field`

- CHANGELOG.md
- src/gleam/result.gleam
- test/gleam/result_test.gleam
This PR introduces the `result.partition` function; it behaves like `result.all` but instead of short circuiting at the first error it accumulates all errors in the list of results.
> Result partition

- CHANGELOG.md
- src/gleam/dynamic.gleam
- src/gleam_stdlib.erl
- src/gleam_stdlib.mjs
- test/gleam/dynamic_test.gleam
This PR introduces series of `tupleN_from_list` functions to `dynamic` module. The idea is to add ability to decode list into tuple.
Currently code:
```gleam
import gleam/io
import gleam/dynamic
import gleam/json
pub fn main() {
io.debug(json.decode("[1,2]", dynamic.tuple2(dynamic.int, dynamic.int)))
}
```
Will fail with error:
```gleam
Error(UnexpectedFormat([DecodeError("Tuple of 2 elements", "List", [])]))
```
Now it can be done with `dynamic.tuple2_from_list`:
```gleam
import gleam/io
import gleam/dynamic
import gleam/json
pub fn main() {
io.debug(json.decode("[1,2]", dynamic.tuple2_from_list(dynamic.int, dynamic.int)))
}
```
Result:
```gleam
#(1, 2)
```
Fixes #420
> Introduce ability to decode tuple from list

- src/gleam/bool.gleam
Previously, the doc suggested that the fallback is run if the input is `True`. The actual behavior is the opposite.
> Fix doc for bool.guard

- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/map.gleam
- src/gleam/queue.gleam
- src/gleam/string.gleam
- test/gleam/function_test.gleam
- The documentation of some modules was still referencing the `list.head` and `list.tail` functions instead of `list.first` and `list.rest`
- To make the codebase more consistent and easy to approach I've also replaced all references to `[head, ..tail]` to `[first, ..rest]` so the naming scheme is consistent throughout the code and examples. This shouldn't create any merge conflict with already open PRs; however, I've kept all changes in a single commit that I can revert before merging if you think it's not necessary to update the codebase in this regard
> Replace `list.head` and `list.tail` with `list.first` and `list.rest`

- CHANGELOG.md
- src/gleam/list.gleam
- The `list.shuffle` doc examples were not consistent with the convention used by the standard library
- `list.zip` and `list.strict_zip` called their arguments with different names, since they're almost the same function it would make sense for them to be consistent with the naming. I changed the names of both so that the function signature can read better: `xs` and `ys` were changed in favor of `list` and `other`. I've also added the label `with` to the second argument. This shouldn't be a breaking change since the argument previously didn't have a label so any preexisting code that used `zip` will still work the same
> Fix minor inconsistencies in list module

- src/gleam_stdlib.mjs
This PR cleans up the `gleam_stdlib.mjs` source by running it through Prettier.
The following changes were made:
- Replaced a tab literal with spaces to match the rest of the file
- Added missing semicolons on some lines
> Clean up `gleam_stdlib.mjs` source

- src/gleam/order.gleam
In the module `order` the functions `max` and `min` did not explicitly state which variant is considered to be bigger/smaller, this may lead to confusion regarding their behaviour
> Add description of `Order` ordering

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
If you feel like it could be useful I could also add `map4`, `map5` etc.
> Add `map2` and `map3` to `list` module

- src/gleam/list.gleam
In my `map2` PR I inadvertently used a special character that prevents the markdown doc of map2 to render correctly
> Remove special character from `map2`'s doc

- .github/workflows/ci.yml
- CHANGELOG.md
- src/gleam_stdlib.erl
- test/gleam/string_test.gleam
Replaces https://github.com/gleam-lang/stdlib/pull/447
> Handle inspect on Erlang atoms (that can be created from strings in Gleam), that are invalid in Gleam.

- src/gleam/list.gleam
If items collected into a list going not from the start but from the end then there is no need to call `reverse`.
> Remove need for reverse in `list.range`

- CHANGELOG.md
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- test/gleam/iterator_test.gleam
- test/gleam/list_test.gleam
As @vonagam pointed out in #474 `iterator.flatten` is not consistent with `list.concat`, this PR deprecates `iterator.flatten` in favour of `iterator.concat`
> Sort out the `flatten`/`concat` naming convention for iterators and lists

- src/gleam/string.gleam
The slice function docs implied it could get two indexes, when it should get a start index and a length.
> Update string.slice docs

- CHANGELOG.md
- src/gleam/iterator.gleam
- test/gleam/iterator_test.gleam
The suggestion to add a `zip_with` presented in PR #365 lead to adding `list.map2`; adding `iterator.map2` with the same behaviour would also make sense to me!
By the way, in the doc examples I've used the new style proposed in #490; if you prefer, I can stick with the old one for consistency :)
> Add `iterator.map2`

- CHANGELOG.md
- src/persistent-hash-map.mjs
- test/gleam/map_test.gleam
This is an attempt at a fix for #497. Both JS and Erlang target tests pass.
> Fix map equality checking when the amount of keys differs

- src/gleam/result.gleam
I found result.try confusing when I had not realized that it could "replace" an `Ok` with an `Error`. I also did not understand its use in function chaining because I hadn't seen an example of a function call creating the result that it takes as input. This changes the description to be more precise about what result.try does, and to show examples of use that will hopefully demonstrate its value more clearly.
> Update result.gleam to clarify try and add examples of use

- CHANGELOG.md
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/map.gleam
- src/gleam/set.gleam
- test/gleam/set_test.gleam
This PR closes #502 by renaming the `for` labels in the `{thing}.filter` functions to `keeping`
> Rename `{thing}.filter` predicate's label 

- src/gleam/list.gleam
I found this example was broken when I was exploring the `stdlib` today.
The previous version wouldn't compile and was using argument labels that don't exist on `list.group`.
Updated version seems to return the expected value shown in the comment below the code.
> docs: Fix list.group example

- src/gleam/dynamic.gleam
This fixes some display issues in the docs for the examples for the `dynamic.tuple4`:
*Old*
*New*
And separates and formats 2 examples for `dynamic.tuple5`:
*Old*
*New*
> Fix formatting in docs for dynamic

- CHANGELOG.md
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- test/gleam/iterator_test.gleam
- test/gleam/list_test.gleam
Changed `list.index_map` callback signature to `fn(a, Int) -> b` from `fn(Int, a) -> b`, to be consistent with `list.index_fold`.
> list.index_map: change callback signature

- src/gleam/bit_array.gleam
- src/gleam/bool.gleam
- src/gleam/dict.gleam
- src/gleam/dynamic.gleam
- src/gleam/float.gleam
- src/gleam/function.gleam
- src/gleam/int.gleam
- src/gleam/io.gleam
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/option.gleam
- src/gleam/order.gleam
- src/gleam/pair.gleam
- src/gleam/queue.gleam
- src/gleam/regex.gleam
- src/gleam/result.gleam
- src/gleam/set.gleam
- src/gleam/string.gleam
- src/gleam/string_builder.gleam
- src/gleam/uri.gleam
Right now all examples are like this:
```gleam
> fold(over: [1, 2, 3], from: 0, with: fn(x, y) {
>   x + y
> }
6
```
This is a bit frustrating since it messes with syntax highlighting and one cannot simply copy and paste the code to try it.
In this PR I've changed all code examples to follow the style suggested in #490;
I think it is a nice quality of life improvement while we wait for doc tests.
I've also fixed a couple of doc examples that wouldn't compile.
> Make doc examples consistent in style

- CHANGELOG.md
- src/gleam/set.gleam
- test/gleam/set_test.gleam
While working on a different Gleam project, I noticed there wasn't a quick way to do a difference from one set to another. Figured this could be nice quality of life addition to the set module.
> Add set difference function

- src/gleam/set.gleam
There's a recently merged example which is using the previous style for doc example, I changed it to make it consistent with the rest of the documentation examples
> Change doc example style

- CHANGELOG.md
- src/gleam/bit_array.gleam
- src/gleam_stdlib.mjs
- test/gleam/bit_array_test.gleam
Proposal for `bit_array.inspect` function.
Details:
- `bit_array.inspect` gives output identical to `string.inspect` (in the case when the bits aren't valid UTF-8).
- Handles partial bytes
- Added tests and updated changelog
> Add bit_array.inspect function

- src/gleam_stdlib.mjs
- test/gleam/dynamic_test.gleam
null object possibly obtained when decoding JSON.
Solves #528
> Fix: do not crash w/ TypeError when field decodes a null object

- CHANGELOG.md
- src/gleam_stdlib.erl
- test/gleam/dynamic_test.gleam
Hi. I noticed that the boolean type is incorrectly classified on the beam runtime. This should fix it.
> Fix boolean classification

- CHANGELOG.md
- src/gleam/bool.gleam
> Deprecate `bool.min` and `bool.max`

- CHANGELOG.md
- src/gleam/regex.gleam
- src/gleam_stdlib.mjs
- test/gleam/regex_test.gleam
Fixes #561
Only happens when the regex to split with has an optional match which isn't present.
For consistency with the Erlang target, we replace `Nil` (`undefined`) with `""`.
> Fix `regex.split` including `Nil` in the returned `List(String)` on JS

- src/gleam/set.gleam
Add the missing doc comment describing the drop function in set module. This was the only missing documentation on the set module, besides the module documentation comment, which I'm not sure if something we would like to add as well?
> Add doc comment to set.drop

- src/gleam/list.gleam
- test/gleam/list_test.gleam
Adds `list.wrap` and tests.
For context, see issue discussion: https://github.com/gleam-lang/stdlib/issues/569.
> Add `list.wrap`

- CHANGELOG.md
- src/gleam_stdlib.erl
- test/gleam/string_test.gleam
Addresses https://github.com/gleam-lang/stdlib/issues/585.
> Escape form feed control character in string.inspect on Erlang

- CHANGELOG.md
- src/gleam/list.gleam
This PR changes the implementation of `list.sort` to improve its performance on (pre)sorted lists (~10x)!
> Improve performance of `list.sort` for (pre)sorted lists

- CHANGELOG.md
- src/gleam_stdlib.mjs
- test/gleam/bit_array_test.gleam
> Fix `bit_array` slices of slices on JavaScript

- test/gleam/float_test.gleam
OTP v27.0 changed floating point behavior, such that 0.0 and -0.0 have distinct internal representations and are no longer considered equal.
Details:
https://erlang.org/documentation/doc-15.0-rc1/doc/upcoming_incompatibilities.html#0-0-and-0-0-will-no-longer-be-exactly-equal
> fixed test to float.negate after changes to OTP

- src/gleam/set.gleam
It seems like the return value for this example is wrong here even though I haven't run the code locally to double-check yet.
> Fix set.symmetric_difference docs

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
An attempt at implementing `list.count` and `iterator.count` as suggested in #592.
The functions will return the number of elements in a given list/iterator that satisfy the given predicate.
> list.count

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
- Fix for #612 , it makes the return value of this edge case default to an empty list
> Fix infinite recursion loop in `list.window` when `by` is 0

- src/gleam/iterator.gleam
Fix an incorrect example in the `iterator.last` docs
> Fix incorrect example in the `iterator.last` docs

- CHANGELOG.md
- src/gleam/iterator.gleam
- test/gleam/iterator_test.gleam
Closes #624
When using the `iterator.yield` function, yield the value without waiting for the next one to become available.
> Don't wait for next value in iterator.yield

- CHANGELOG.md
- src/gleam/set.gleam
- test/gleam/set_test.gleam
I had initially thought of proposing also adding `dict.map_keys()` and then implementing `set.map()` in terms of that function, but as I thought about it more, I couldn't think of a strong reason to add that other than just doing it for completeness' sake, so I did it in terms of `set.fold()` instead.
Resolves #636.
> Add set.map().

- CHANGELOG.md
- src/gleam/bit_array.gleam
- src/gleam_stdlib.erl
- src/gleam_stdlib.mjs
- test/gleam/bit_array_test.gleam
Fixes #642.
This replaces the implementation of Base64 encoding with a native JS implementation that is significantly faster, 13-14x in my benchmarks. It's based on https://github.com/mitschabaude/fast-base64/blob/main/js.js.
The new implementation works on large inputs, this was tested up to 128MiB on Node.js 22 with no issues.
The Erlang implementation also now gets `base64:encode` to add the padding to the returned string if it's requested, which optimises away a `string.replace` when padding isn't desired.
> Base64 encoding optimisations. Fix encoding of large bit arrays on JS.

- CHANGELOG.md
- src/gleam_stdlib.mjs
- test/gleam/bit_array_test.gleam
This improves Base64 decoding speed on JavaScript by 5-30x in my benchmarks, with the greatest improvement seen on larger input sizes.
This PR also adjusts a recently added test that was causing the test suite to take 25 (!) minutes on Node.js versions prior to 22.0. This was caused by `string.length` being extremely slow on long strings on older Node.js versions, which I haven't investigated further at this stage.
---
Speedup with 8 byte input: 5x
Speedup with 64 byte input: 16x
Speedup with 1KiB input: 23x
Speedup with 1MiB input: 29x
Speedup with 16MiB input: 30x
Tested on Node.js 22 on a MacBook Pro M2.
> Improve Base64 decoding performance on JavaScript

- CHANGELOG.md
- src/gleam_stdlib.mjs
- test/gleam/float_test.gleam
> Fix `float.parse` failing to parse exponential notation on JavaScript

- src/gleam/int.gleam
Fixed typo in docs for absolute_value func in int module. It should be 12, but 2.
> Fixed typo in docs for absolute_value func in int module.

- .github/workflows/ci.yml
- test/gleam/bit_array_test.gleam
- Runs tests on Erlang 26 & 27, Node.js (18, 20 & 22), Bun (v1), and Deno (v1).
- Node.js 16 was being used to run tests before, but this has been dropped as it's out of security support.
- Added an extra base 64 decoding test added that wasn't possible before because of differences on Node 16.
I think there's a required status check in the GitHub settings that will need updating if this is merged, currently this PR shows "Required statuses must pass before merging" referring to a `test` job that doesn't exist anymore.
> Run CI on all supported runtimes

- src/gleam/bit_array.gleam
- src/gleam/dynamic.gleam
- src/gleam/float.gleam
- src/gleam/string.gleam
- src/gleam/string_builder.gleam
- src/gleam/uri.gleam
- test/gleam/bit_array_test.gleam
I've removed as many `target` annotations as I could. Some are still left in tests (but that makes sense since we want to check different behaviours on different targets) and in some modules but those are way less frequent now :)
> Remove target annotations

- src/gleam/dict.gleam
I think there was a small typo in the dict examples.
> fix typo in dict examples

- src/gleam/order.gleam
Deletes duplicate `negate(Lt)` example in **gleam/order**. Replaces it with `negate(Gt)` to exhaustively complete the examples.
> Deduplicate gleam/order negate examples

- src/gleam/float.gleam
- test/gleam/float_test.gleam
Should close #525 by adding the `float.modulo` function.
I also tried implementing the `float.remainder` function as:
``` gleam
pub fn modulo(dividend: Float, by divisor: Float) -> Result(Float, Nil) {
case divisor {
0.0 -> Error(Nil)
_ -> Ok(dividend -. round(dividend /. divisor) *. divisor)
}
}
```
But `round` returns an `Int` and I could not find an easy way to convert it back to `Float`. A little bit off-topic, but why does it return an `Int` it should return a `Float` right?
> Add float.modulo

- src/gleam/uri.gleam
- test/gleam/uri_test.gleam
`uri.origin` should not include a trailing slash - I've corrected the relevant tests and updated the function to `concat` its own results, as this behaviour appears specific to the `origin` function only, not `to_string`.
Additionally, I've added two tests to cover the default port stripping when `http` or `https` are supplied along wtih port `80` or `443` respectively.
Fixes https://github.com/gleam-lang/stdlib/issues/623.
> Correct implementation of uri.origin and add tests for default ports

- CHANGELOG.md
- src/gleam/dynamic.gleam
- test/gleam/dynamic_test.gleam
As discussed on Discord, I believe the `dynamic.optional_field` behaviour is a bit off and this PR tries to adjust it to match the documented behaviour.
The use of `decode_optional` in the implementation meant that the value was optional as well as the key which means that each use of `optional_field` was implicitly wrapping its value decoder in `dynamic.optional`.
Awkwardly this is a breaking change in behaviour but not in types. We can now get `Some(None)` back which I don't think was previously possible and we get an error in situations where we didn't before.
I'm not sure if the per-target tests is how you like to manage that situation.
> Adjust dynamic.optional_field to better match documented behaviour

- src/gleam/set.gleam
Unsure why the docs was using the wrong argument name here, but this PR fixes the small typo to prevent confusion :)
> Fixing wrong argument name in the doc example for set.filter

- src/gleam_stdlib.mjs
- test/gleam/string_test.gleam
JS uses the comma by default when no separator is passed to `Array.prototype.join` so `unicode_whitespaces` is ` ,\t,\n,\x0B,\f,\r,\x85, , ` rather than just a string of whitespaces.
Fixed by passing an empty string to `join`.
> fix: Fix js trim implementation removing commas

- src/gleam_stdlib.erl
While parsing Gleam code with glexer, I noticed that ~75% of the total runtime of my program was spent in `unicode:characters_to_binary/2`.
After investigating, I've found that glexer is basically a big `string.pop_grapheme` loop, which in turn calls `unicode:characters_to_binary` twice on the result of `string:next_grapheme`, once on the popped character, and once on the remaining string. `characters_to_binary` seems to at least loop once through the string to check if its valid UTF-8. 
According to the [docs](https://www.erlang.org/doc/apps/stdlib/string.html#next_grapheme/1), next_grapheme returns the character as a charlist, but the remaining string as a binary. Just to be sure, I've added a guard to make sure the old behaviour is triggered if `next_grapheme` happens to not return a …
> Improve `string.pop_grapheme` performance

- .github/dependabot.yml
- .github/workflows/ci.yml
There are several changes:
- `workflow_dispatch:` allows to run this job from the admin panel, which is nice to have for debugging sessions. Never know when you might need it
- `timeout-minutes: 15` added to each job. By default there's basically no timeout. Since all jobs pass in less than a minute, 15 mins is a good enough space to fit
- `fail-fast: false` added to matrix jobs, so if one fails, others won't be canceled. This is very useful for debugging and give a lot more information about what is going on. Basically, this should be the default for all actions
- `permissions:` enhances the security, is set to the minimal set of permissions possible. See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/assigning-permissions-to-jobs
- `concurrency:` …
> Update GitHub Actions

- CHANGELOG.md
- src/gleam/bit_array.gleam
- src/gleam_stdlib.erl
- src/gleam_stdlib.mjs
- test/gleam/bit_array_test.gleam
All credit for the implementation goes to @RGBboy
I changed some details, main ones are:
- I use pattern matching instead of a `bit_array_to_int` function call 
- No more panics
- Tie is lazy evaluated in my version
- Improved naming in some places
I think that the main use-case for this is sorting text entries from APIs that return bit arrays. 
Please, suggest more ideas for test cases and docs!
Closes #679
> Add `bit_array.compare`

- src/gleam/bytes_builder.gleam
This looks like a copy-paste error from string_builder. BytesBuilder is used to construct binary content rather than text content.
Other options:
"...efficiently building BitArrays"
"bytes content"
> Update BytesBuilder docstring to reflect binary content, net text

- CHANGELOG.md
- src/gleam_stdlib.mjs
This speeds up many string functions including `string.length()`, `string.graphemes()`, `string.pop_grapheme()`, and any functions that call them, e.g. `string.slice()`.
In one app I work on this change reduced the runtime of a piece of string-heavy code from 5.6s to 2.0s.
> Improve JS string performance by caching the Intl Segmenter

- src/gleam/int.gleam
InvalidBase can no longer be returned from the function since e174d4eea80dcf28f72c30d78cc17493998687aa (#673).
> Fix documentation for int.undigits

- CHANGELOG.md
- src/gleam/string.gleam
Using the native repeat function is meaningfully faster.
> Optimise string.repeat on JS target

- src/gleam/string.gleam
- src/gleam_stdlib.mjs
Noticed in some benchmarks on the JS target that the current implementations of `string.pad_left()` and `string.pad_right()` are substantially slower than native `String.padLeft()` and `String.padRight()`.
This PR switches to using the native functions instead, and all the existing tests pass without any changes.
In my project this took total runtime from ~13s to ~3s.
> Optimise string.pad_left, string.pad_right, string.slice

- src/gleam/bool.gleam
- src/gleam/dict.gleam
- src/gleam/dynamic.gleam
- src/gleam/iterator.gleam
- src/gleam/list.gleam
- src/gleam/option.gleam
- src/gleam/queue.gleam
- src/gleam/regex.gleam
- src/gleam/result.gleam
- src/gleam/string.gleam
- src/gleam/string_builder.gleam
- src/gleam/uri.gleam
This PR contains many small refactorings to make sure the stdlib follows a consistent style:
- type variables for collection items are `a`, `b`, ...
- type variables for errors are `e`, `f`, ...
- type variables for dicts or key-value things are `k` and `v`
- when pattern matching on a list it's always `[first, ..rest]` instead of `[x, ..XS]`
- in public apis argument names are full words instead of single letters (e.g. `first(s: String)` becomes `first(string: String)`)
- I've added type signatures in a couple top level functions that didn't have it
- I've removed an unused import from the `iterator` module
The only exceptions are the `set` and `iterator` modules where the type variable seems to almost always be called `member` and `element` respectively instead of a plain `a`. So I …
> Small refactorings

- src/gleam/result.gleam
I found myself using `result.try_recover` like this, where I was ignoring the error value returned:
```gleam
import gleam/result
pub fn main() {
use _ <- result.try_recover(Error(1))
use _ <- result.try_recover(Error(2))
Error(3)
}
```
Later, I found I could use `result.lazy_or`:
```gleam
import gleam/result
pub fn main() {
use <- result.lazy_or(Error(1))
use <- result.lazy_or(Error(2))
Error(3)
}
```
... and I didn't need to use `_` to omit anything, as it does not provide the error value, which fit my use case better.
Maybe the wording can be improved, but I think this might be something worth calling out in the docs.
> Hint at user when to use `result.lazy_or` vs `result.try_recover`

- src/gleam/bool.gleam
We can use built-in bool operators to perform bitwise operations. This also makes it more readable.
> enhance bitwise operators with built-in bool operators

- CHANGELOG.md
- src/gleam_stdlib.mjs
- test/gleam/float_test.gleam
- test/gleam/string_test.gleam
Improve `float.to_string` handling of exponentials and sings. Address https://github.com/gleam-lang/stdlib/issues/694.
Before this PR `float.to_string(1.0e123)` would output `1e+123.0`.
> Improve `float.to_string` on JavaScript

- CHANGELOG.md
- src/gleam/set.gleam
- test/gleam/set_test.gleam
Found myself needing this while working on a project, saw that `list` and `dict` had equivalent functions, so I thought it would be nice if `set` had one too.
Implementation, documentation and test adapted from the `list` and `dict` equivalents.
> Add `set.each` function

- CHANGELOG.md
- src/gleam/bytes_builder.gleam
- src/gleam/bytes_tree.gleam
- src/gleam/dynamic.gleam
- src/gleam/string.gleam
- src/gleam/string_builder.gleam
- src/gleam/string_tree.gleam
- src/gleam/uri.gleam
- test/gleam/bytes_tree_test.gleam
- test/gleam/string_tree_test.gleam
> Rename string and array builder to tree

- src/gleam/list.gleam
Reworded the summary line to use similar structure as other function summaries in the list module and made the note about not preserving initial value order be more specific.
While in hindsight it makes sense what "does not preserve" means, and it can also be deducted from the supplied examples, at least for me it wasn't obvious at first glance and I ended up looking at the source code for answers.
> Clarify documentation for 'list.group'

- src/gleam/uri.gleam
- src/gleam_stdlib.erl
- src/gleam_stdlib.mjs
- test/gleam/uri_test.gleam
This PR closes #734
~~This version that's using `pop_grapheme` is about 10x slower than the implementation that uses a regex, which is unfortunate.~~
I've managed to make this (thanks to @joshi-monster!!) as fast as the implementation using regexes!!
> Remove regex dependency from uri module

- src/gleam/bit_array.gleam
- src/gleam/dict.gleam
- src/gleam/dynamic.gleam
- src/gleam/float.gleam
- src/gleam/int.gleam
- src/gleam/io.gleam
- src/gleam/regex.gleam
- src/gleam/string.gleam
- src/gleam/string_tree.gleam
- src/gleam/uri.gleam
As discussed [on discord](https://discord.com/channels/768594524158427167/768594524158427170/1311459444537692261). This PR removes most of the `do_*` functions, and makes the public functions external directly. There were a few cases where the Gleam argument order was different to the argument order of the external function that was being called, and so I had to leave it (e.g. `dict.filter`)
> Replace `do_*` with direct externals

- CHANGELOG.md
- src/gleam/bit_array.gleam
- src/gleam/bytes_tree.gleam
- src/gleam_stdlib.erl
- test/gleam/bit_array_test.gleam
- test/gleam/bytes_tree_test.gleam
This PR makes a few updates prior to then bringing in support for unaligned bit arrays on JavaScript as a follow-up step.
Specifically:
- Adds the `bit_array.pad_to_bytes` function. Is this name ok?
- The `base64_encode`, `base64_url_encode`, and `base16_encode` functions now pad with zeros prior to encoding. This is only relevant on the Erlang target at present. Fixes #750.
- `bytes_tree` now pads bit arrays to whole bytes when they're added to the tree. This is a breaking change in behaviour on Erlang, but is what it is documented as doing. Fixes #320.
Also:
- The bit array tests have been expanded to have more tests of unaligned bit arrays on the Erlang target.
- The `bit_array_int_to_u32/1` and `bit_array_int_from_u32/1` functions in `gleam_stdlib.erl` have been garbage collected as …
> Add `bit_array.pad_to_bytes`. Pad bit arrays when encoding and when used in `bytes_tree`.

- CHANGELOG.md
- src/dict.mjs
- test/gleam/dict_test.gleam
The dict equality check now returns false as soon as any item doesn't match, rather than continuing to unnecessarily check remaining items.
> Optimise dict equality check on JavaScript

- src/gleam/string_tree.gleam
I noticed that there was a doc comment out of place, documenting a private type rather than the public function which it is supposed to document. This PR fixes that.
> Fix doc comment

- CHANGELOG.md
- src/gleam/list.gleam
Avoid calling `list.length` on the lists being zipped.
> Improve the performance of `list.strict_zip`

- CHANGELOG.md
The deprecated function was `to_int`, not `to_string` as stated in the changelog.
> Fix 0.47 changelog

- src/gleam/list.gleam
- test/gleam/list_test.gleam
Inspired by my advent of code 2024 experiences. I often find myself reinventing `list.min` and `list.max` with `fold` and `reduce`, so I thought maybe it'd be nice to just promote these.
PR Adds `list.min` and `list.max` to `gleam/list`.
Like the name suggests, it returns the max/min element in the list, using the passed in comparator. These are slightly higher level abstractions than `reduce` as it takes in comparator functions, which can help with ergonomics at many places.
> add `max` to gleam/list

- CHANGELOG.md
- src/gleam/float.gleam
- src/gleam/list.gleam
- src/gleam_stdlib.mjs
- test/gleam/float_test.gleam
- test/gleam/list_test.gleam
I implemented the sample function based on the discussion in issue #683
This PR contains an implementation of [Algo L](https://en.wikipedia.org/wiki/Reservoir_sampling#Optimal:_Algorithm_L)
I also tested Algo R but it was slower
Algo L requires `log` and `exp`, hence their addition to the float modulet
> Add `sample` function to List module, add `log` and `exp` functions to Float module

- src/gleam/dynamic/decode.gleam
Hi!
There is a missing `decode.success` in this example.
Thanks for the new API by the way, it's lovely.
> Fix dynamic/decode field function example

- CHANGELOG.md
- src/gleam/float.gleam
- test/gleam/float_test.gleam
significantly improve the precision when rounding with a positive precision. while factors greater than one can be accurately represented up to a large number (10, 100, 1000, ...), even a factor of 0.1 already introduces inaccuracies, since 0.1 cannot be accurately represented using floating-point numbers.
The added test cases show this behaviour; one of them always fails if both branches of the `case` were the same.
~ :purple_heart:
> improve precision of `float.to_precision`

- CHANGELOG.md
- src/gleam/string.gleam
- test/gleam/string_test.gleam
- Treats U+FFFE and U+FFFF as valid unicode codepoints rather than errors.  See #778.
- Adds tests for the important boundary values
> Fix non-character handling in `string.utf_codepoint`

- src/gleam/dynamic/decode.gleam
Just a quick fix to the documentation for `dynamic/decode`. Specifically removing references to the `decode/zero` package and fixing some typos.
> Fix decode.recursive documentation

- CHANGELOG.md
- src/gleam_stdlib.mjs
First of all, I really appreciate all the work that the core members have put into gleam, it's a super fun and refreshing language.
This PR should fix `io.print` when targeting javascript and compiling with bundlers like vite, where the process object exists but doesn't contain a `stdout` object.
> Fix print when using bundlers

- CHANGELOG.md
- src/gleam/list.gleam
This PR closes #667. Huge thank you to @radekm for bringing this up! I've picked up the work as they said they don't have a lot of time one their hands.
> Fix implementation of `list.unique`

- CHANGELOG.md
- src/gleam/bit_array.gleam
- src/gleam/bytes_tree.gleam
- src/gleam/dict.gleam
- src/gleam/dynamic/decode.gleam
- src/gleam/float.gleam
- src/gleam/int.gleam
- src/gleam/list.gleam
- src/gleam/option.gleam
- src/gleam/string.gleam
- src/gleam/uri.gleam
- test/gleam/list_test.gleam
- test/gleam/should.gleam
reading through the stdlib code I noticed a couple of inconsistencies and code patterns that didn't look great to me. A recap of the changes introduced by this PR:
- I've made sure that pattern matching on lists follows the usual `[first, ..rest]` pattern instead of using single letter variables
- Fixed the implementation of `list.key_set` to be tail recursive
- Removed trailing spaces from various lines
- Stop using the catch all pattern when pattern matching on `Result`s, `Bool`s or `List`s
- I've removed the `reverse_loop` function in favour of the better named `reverse_and_prepend` one to use internally in the list module, they did the same thing
> Various changes

- CHANGELOG.md
- src/gleam/list.gleam
This PR closes #773
I couldn't come up with a better deprecation message though!
> Deprecate `list.pop` and `list.pop_map`

- src/dict.mjs
- src/gleam_stdlib.mjs
This lets the Javascript minifiers remove these constants from the final bundle
> Annotate javascript constants as pure

- src/gleam/uri.gleam
Thanks to upcoming call graph usage detection, I noticed that this function is not used anywhere.
> Remove unused `extra_required` function

- CHANGELOG.md
- src/gleam/io.gleam
This can be merged only after <https://github.com/gleam-lang/gleam/pull/3676> has been merged.
> deprecate `io.debug` in favour of `echo`

- src/gleam/dynamic/decode.gleam
- src/gleam_stdlib_decode_ffi.mjs
- test/gleam/dynamic/decode_test.gleam
Hi!
- String decoders are false in JS FFI, leading to inconsistent code, and potentially runtime errors (`decode.string |> decode.map(string.lowercase)` creates a runtime error).
- Closes #806.
> `gleam/dynamic/decode` bugfixings

- CHANGELOG.md
- src/gleam/string.gleam
I do not know why this was implemented using string_builder. Maybe I'm missing some context here?
Anyways here are some numbers. Each benchmarked run is 1000 string appends.
```
10 / 10             stdlib string.append   116865.2340        0.0067        0.0139
10 / 10             gleam string.append   1376350.3739        0.0005        0.0007
10 / 100            stdlib string.append   107510.2501        0.0066        0.0139
10 / 100            gleam string.append   1373745.9937        0.0005        0.0008
10 / 1000           stdlib string.append   101007.7914        0.0066        0.0152
10 / 1000           gleam string.append   1372307.2543        0.0005        0.0008
100 / 10            stdlib string.append    95415.4526        0.0066        0.0140
100 / 10            gleam string.append …
```
> improve performance of string.append

- CHANGELOG.md
- src/gleam/string.gleam
- test/gleam/string_test.gleam
On the javascript target, this is ~40% improvement:
```
Input               Function                       IPS           Min           P99
10 / 10             stdlib string.concat  1896794.4060        0.0001        0.0003
10 / 10              gleam string_concat  2612378.6181        0.0001        0.0002
10 / 100            stdlib string.concat   459578.7508        0.0011        0.0026
10 / 100             gleam string_concat   663753.4921        0.0008        0.0019
10 / 1000           stdlib string.concat    47628.1946        0.0112        0.0336
10 / 1000            gleam string_concat    82032.8985        0.0077        0.0148
100 / 10            stdlib string.concat  1984712.2048        0.0001        0.0002
100 / 10             gleam string_concat  2604517.0489        0.0001 …
```
> improve performance of `string.concat`

- CHANGELOG.md
- src/gleam/string.gleam
- src/gleam_stdlib.mjs
- test/gleam/string_test.gleam
This is a similar situation to `string.concat`, however I do not know about a BIF we could use here so the Gleam implementation is actually best.
There is also a FFI version for Javascript, but even that is slower than a pure Gleam solution now, most likely due to the recent improvements to list pattern matching in 1.9.
For the benchmark numbers, I chose to join on `, `, since I believe a short character join string is the most common case.
Numbers!
```
Input               Function                       IPS           Min           P99
10 / 10             stdlib string.join     777191.7326        0.0009        0.0015
10 / 10             gleam string.join     1630428.8300        0.0005        0.0011
10 / 100            stdlib string.join     150520.7347        0.0054        0.0150
10 / 100 …
```
> improve performance of string.join

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/bit_array_test.gleam
I went over the list module and found some functions that weren't implemented with the usual `_loop` pattern and changed those. In doing so I've also made `combinations` tail recursive, it was not previously
Ah and I've changed some bit array segments that were implicitly truncated to their truncated value that's actually used!
> Various changes to the list module

- src/gleam/list.gleam
list.concat was deprecated and now fully removed, this change removes a reference to it in `list.flatten`'s documentation
> Doc: Remove reference to list.concat in documentation

- CHANGELOG.md
- src/gleam/option.gleam
- src/gleam/result.gleam
In this PR I've changed the implementation of the `option.values` and `option.all` functions to be tail recursive.
> Optimise option functions

- src/gleam/list.gleam
Erlang actually provides a BIF for flatten (called append) that allows it to only traverse each element once instead of twice.
> Use erlang's lists:append/1 for list.flatten

- src/gleam/dynamic.gleam
- src/gleam/list.gleam
- src/gleam/option.gleam
- src/gleam/string.gleam
- src/gleam_stdlib.mjs
Just a few random typos I found when reading the source code with a spell checker enabled in my editor.
Aside: https://github.com/gleam-lang/stdlib/blob/a108983548a0bc66a1fa36ca008361b0fb8a86a1/src/gleam_stdlib.mjs#L123-L124 NodeJS 14 has been EOL for a little over two years now.
> Fix a few typos

- CHANGELOG.md
- src/gleam_stdlib.mjs
NodeJS 14 [has been EOL] for a little over two years now (with the last update to it being on 2023-02-16).
[has been EOL]: https://nodejs.org/en/about/previous-releases#:~:text=v14
> Remove the fallback for NodeJS 14 from `string.replace()`

- CHANGELOG.md
- src/gleam/list.gleam
- test/gleam/list_test.gleam
A couple of improvements here:
- I've changed the `sample` labels to be consistent with similar stuff like `take` and `drop`, this should also make it easier to see that it might not always return `n` elements
- I've added a link to the algorithm L documentation
- The reservoir building is more efficient as it's no longer using `list.range` and `list.map2`, but building it in one go
- There was a bug in the sampling algorithm where it could end up taking the same item twice from the list so I've updated it and made the tests more specific
> Improve `list.sample` docs and implementation

- src/gleam/string.gleam
- test/gleam/string_test.gleam
Avoid calling `string.slice` when `num_graphemes` is equal to `0`, making `string.drop_end` constant for that case.
Nothing was broken before, but I added tests because I like testing right on the boundary.
Seems like too tiny of a change to mention in the `CHANGELOG.md`, so I skipped it.
> Fix `string.drop_end` to handle zero gracefully
