.gitignore, gen/src/gleam@list.erl, gen/src/gleam@string.erl, src/gleam/atom.gleam, src/gleam/dynamic.gleam, src/gleam/function.gleam, src/gleam/list.gleam, src/gleam/map.gleam, src/gleam/result.gleam, src/gleam/string.gleam
Added the docs to string module with a proposed flesh out API as discussed.l
Also added type signatures for the rest of the modules.
=> Proposed string module docs.  Types for other modules

src/gleam/atom.gleam, src/gleam/bool.gleam, src/gleam/dynamic.gleam, src/gleam/float.gleam, src/gleam/function.gleam, src/gleam/int.gleam, src/gleam/iodata.gleam, src/gleam/list.gleam, src/gleam/order.gleam, src/gleam/pair.gleam, src/gleam/result.gleam
A few of the larger modules aren't done, and I've chosen to not document Exception as it seems to be moving.
#9
=> More documentation for many modules

CHANGELOG.md, gen/src/gleam@string.erl, gen/test/gleam@string_test.erl, src/gleam/string.gleam, src/gleam_stdlib.erl, test/gleam/string_test.gleam
Implementing String.contains/2 and String.repeat/2
Lemme know if this sort of thing is welcome or if there's better process to follow! Happy to help where I can!
=> Implementing String.contains and String.repeat

src/gleam/map.gleam
I hope these are correct. I may have missed something which makes them valid but seems like they are to be corrected?
=> Fix minor typos in map docs

CHANGELOG.md, gen/src/gleam@string.erl, gen/test/gleam@string_test.erl, src/gleam/string.gleam, test/gleam/string_test.gleam
Added string.trim_left & string.trim_right functions.
=> string.trim_left & string.trim_right

CHANGELOG.md, gen/src/gleam@string.erl, gen/test/gleam@string_test.erl, src/gleam/string.gleam, src/gleam_stdlib.erl, test/gleam/string_test.gleam
Added string.starts_with & string.ends_with functions.
This resolves https://github.com/gleam-lang/stdlib/issues/39
=> string.starts_with & string.ends_with

CHANGELOG.md, gen/src/gleam@string.erl, gen/test/gleam@string_test.erl, src/gleam/string.gleam, test/gleam/string_test.gleam
Added string.slice function.
This resolves https://github.com/gleam-lang/stdlib/issues/42
=> string.slice

CHANGELOG.md, gen/src/gleam@string.erl, gen/test/gleam@string_test.erl, src/gleam/string.gleam, src/gleam_stdlib.erl, test/gleam/string_test.gleam
Added `string.pad_left` and `string.pad_right` functions.
=> string.pad_left & string.pad_right

CHANGELOG.md, src/gleam/string.gleam, test/gleam/string_test.gleam
I added string.drop_left & string.drop_right.
This follows naturally from: https://github.com/gleam-lang/stdlib/pull/43
=> string.drop_left & string.drop_right

CHANGELOG.md, src/gleam/string.gleam, src/gleam_stdlib.erl, test/gleam/string_test.gleam
=> string.pop_grapheme

CHANGELOG.md, src/gleam/os.gleam, src/gleam/string.gleam, test/gleam/os_test.gleam, test/gleam/string_test.gleam
includes `split_once` function for strings
=> Add os module

CHANGELOG.md, src/gleam/uri.gleam, test/gleam/uri_test.gleam
Reopens #69 
I have changed let to assert
=> Uri utilities

CHANGELOG.md, src/gleam/io.gleam
I assume this is what is wanted because you talk about piping in the docs
=> return value from debug so it can be piped

src/gleam/atom.gleam
=> Spelling correction

CHANGELOG.md, src/gleam/list.gleam, test/gleam/list_test.gleam
=> Add pop utility functions for lists

CHANGELOG.md, src/gleam/regex.gleam, src/gleam_stdlib.erl, test/gleam/regex_test.gleam
Added regex.split & regex.scan.
The interface is based on: https://package.elm-lang.org/packages/elm/regex/latest/Regex
=> regex.split & regex.scan

src/gleam/string.gleam, src/gleam/uri.gleam
Refactor string, uri
Overhaul uri.merge
=> Refactor string, uri

src/gleam/bit_builder.gleam, src/gleam/dynamic.gleam, src/gleam/float.gleam, src/gleam/int.gleam, src/gleam/iterator.gleam, src/gleam/queue.gleam, src/gleam/set.gleam, src/gleam/string.gleam, src/gleam/uri.gleam, test/gleam/atom_test.gleam, test/gleam/bit_builder_test.gleam, test/gleam/function_test.gleam, test/gleam/map_test.gleam, test/gleam/queue_test.gleam, test/gleam/regex_test.gleam, test/gleam/string_builder_test.gleam, test/gleam/uri_test.gleam
This fixes an incorrect comment for the `square_root` function (thanks for finding this @CrowdHailer!)
Also ran the formatter, since CI was failing.
=> Fix incorrect comment for square_root function

CHANGELOG.md, src/gleam/float.gleam, src/gleam/int.gleam, test/gleam/float_test.gleam, test/gleam/int_test.gleam
=> add negate functions to int and float modules

CHANGELOG.md, src/gleam/function.gleam, test/gleam/function_test.gleam
As discussed here https://github.com/gleam-lang/stdlib/issues/112
Maybe the standard library could have functions for currying.
=> Add function.curryN

CHANGELOG.md, src/gleam/int.gleam, test/gleam/int_test.gleam
This allows us to get the given int value as a float.
=> Add to_float function for int module

.github/workflows/ci.yml, CHANGELOG.md, src/gleam/float.gleam, src/gleam/int.gleam, test/gleam/float_test.gleam, test/gleam/int_test.gleam
New functions for getting the sum of a list of numbers.
Due to cyclical import errors I couldn't use list.fold so I wrote simple recursive helpers
=> Add int.sum and float.sum

CHANGELOG.md, src/gleam/dynamic.gleam, test/gleam/dynamic_test.gleam
=> Add result and typed_result to dynamic

src/gleam/should.gleam
=> Fix rebar3 eunit documentation link

CHANGELOG.md, src/gleam/result.gleam, test/gleam/result_test.gleam
resolves #135  and #136 
Here's an example of using it, which was very helpful. https://github.com/did-app/glance/commit/8fb9b1afaa0d6a72832275a6b545dd2ff2ac731d#diff-aae871ce041a46aa03c90e48be342dacd1280dd111c30ef2ef7ca013ee4d23d3R37-R40
=> Lazy or and unwrap

src/gleam/bool.gleam, test/gleam/bool_test.gleam
Let me know if you'd prefer different names for any of these! (`xnor` versus `exclusive_nor`, etc)
=> Add bool.nor, bool.nand, bool.exclusive_or, and bool.exclusive_nor

CHANGELOG.md
I forgot this in the last PR 😅
=> Update CHANGELOG.md with new bool functions

src/gleam/bool.gleam
=> Fix typo in nand docs (they referenced nor)

CHANGELOG.md, src/gleam/list.gleam, test/gleam/list_test.gleam
Maybe the std lib could use this. Please feel free to reject this PR if this doesn't belong. Thanks.
Add list.permutations
=> Add list.permutations

CHANGELOG.md, src/gleam/float.gleam, src/gleam/int.gleam, test/gleam/float_test.gleam, test/gleam/int_test.gleam
Implements https://github.com/gleam-lang/stdlib/issues/130
=> Add int.clamp and float.clamp

CHANGELOG.md, src/gleam/list.gleam, test/gleam/list_test.gleam
Last one as discussed in https://github.com/gleam-lang/stdlib/issues/153
=> Add list.fold_until

CHANGELOG.md, src/gleam/list.gleam, test/gleam/list_test.gleam
Uses the existing functions from the lists module in erlang.
=> Implement list.drop_while and list.take_while

src/gleam/iterator.gleam, test/gleam/iterator_test.gleam
Adds `iterator.iterate` which is equivalent to Elixir's `Stream.iterate`
=> Add iterator.iterate

src/gleam/iterator.gleam, test/gleam/iterator_test.gleam
Adds `iterator.take_while` and `iterator.drop_while`
=> Add iterator.{take_while, drop_while}

CHANGELOG.md, src/gleam/iterator.gleam, test/gleam/iterator_test.gleam
Adds an iterator counterpart to `list.intersperse`
=> Add iterator.intersperse

CHANGELOG.md, src/gleam/iterator.gleam, test/gleam/iterator_test.gleam
Adds convenience wrappers for single-element and empty iterators
=> Add iterator.{empty, once, single}

CHANGELOG.md, src/gleam/list.gleam, test/gleam/list_test.gleam
Hi
For you consideration. A couple of functions in list to get unique combinations of elements in the list.
Thanks
=> Add list.combinations

CHANGELOG.md, src/gleam/result.gleam, test/gleam/result_test.gleam
Given a list of results e.g. [Ok(1), None, Ok(3)]
Return a list of ok values [1,3]
=> Add result.values

CHANGELOG.md, src/gleam/option.gleam, test/gleam/option_test.gleam
Just like `result.all` but for `option`.
=> Add option.all

CHANGELOG.md, src/gleam/list.gleam, test/gleam/list_test.gleam
Hi
A couple of list functions I'm using. For your consideration.
=> Add list.transpose and list.interleave

CHANGELOG.md, src/gleam/iterator.gleam, test/gleam/iterator_test.gleam
As mentioned in #214 :smile:
Let me know if i'm missing anything, please. I tried to get the doc comments to look nice as well, but the example is a bit big
=> iterator.fold_until

src/gleam/iterator.gleam, test/gleam/iterator_test.gleam
Overlooked in the last correction commit
=> Fix docs and usage for iterator.reduce

src/gleam/base.gleam, src/gleam/bit_builder.gleam, src/gleam/bit_string.gleam, src/gleam/bool.gleam, src/gleam/dynamic.gleam, src/gleam/float.gleam, src/gleam/function.gleam, src/gleam/int.gleam, src/gleam/iterator.gleam, src/gleam/list.gleam, src/gleam/map.gleam, src/gleam/option.gleam, src/gleam/order.gleam, src/gleam/regex.gleam, src/gleam/result.gleam, src/gleam/set.gleam, src/gleam/string.gleam, src/gleam/string_builder.gleam, src/gleam/uri.gleam
Highlights:
- Wrap type names in inline code blocks
- Correct/unify spelling and grammar
- Add missing punctuation
- Fix some missing backticks in inline code blocks
- Move `BitBuilder` description to module level doc
- Simplify some confusingly worded sentences
=> Improve documentation

src/gleam/function.gleam, test/gleam/function_test.gleam
This change adds a new helper to the function module.
=> Add function.constant

src/gleam/list.gleam
Some of the args are in the wrong places.
As raised in Discord.
I think this is right though I'm happy to be corrected!
=> Adjust list.fold examples

src/gleam/dynamic.gleam
and in decode.shallow_list documentation say decode.list is a function
=> Fix copypasta mistake in decode.list documentation

src/gleam/dynamic.gleam
Fixes https://github.com/gleam-lang/stdlib/issues/268
=> Update documentation for dynamic.map

src/gleam/dynamic.gleam
=> fix dynamic.gleam optional example

CHANGELOG.md, src/gleam_stdlib.mjs
=> Fix `string.length` for empty JS strings

CHANGELOG.md, src/gleam_stdlib.mjs, test/gleam/map_test.gleam
=> Fix record-based map keys for JS

CHANGELOG.md, src/gleam/function.gleam, test/gleam/function_test.gleam
Shamelessy stolen and adopted from @hayleigh-dot-dev and https://hexdocs.pm/elixir/main/Kernel.html#tap/2
=> Add function.tap()

src/gleam/float.gleam, src/gleam/int.gleam, src/gleam_stdlib.mjs, test/gleam/float_test.gleam, test/gleam/int_test.gleam
=> Add int/float.random()

CHANGELOG.md, src/gleam/bit_string.gleam, src/gleam/bool.gleam, src/gleam/float.gleam, src/gleam/int.gleam, src/gleam/io.gleam, src/gleam/iterator.gleam, src/gleam/list.gleam, src/gleam/map.gleam, src/gleam/option.gleam, src/gleam/order.gleam, src/gleam/pair.gleam, src/gleam/queue.gleam, src/gleam/regex.gleam, src/gleam/result.gleam, src/gleam/set.gleam, src/gleam/string.gleam, src/gleam/string_builder.gleam
While this can also be done via the built-in syntax it's nice to have
a complete standard library including this function.
Context: https://discord.com/channels/768594524158427167/811254431051808778/961779713347579944
=> feat(list): Add `prepend` to list module

CHANGELOG.md, src/gleam/float.gleam, src/gleam/int.gleam, test/gleam/float_test.gleam, test/gleam/int_test.gleam
Ref: https://discord.com/channels/768594524158427167/811254431051808778/970309828704632863
I hope that you had this in mind
=> safe divisions

CHANGELOG.md, src/gleam/string.gleam, test/gleam/string_test.gleam
Ref: https://github.com/gleam-lang/stdlib/issues/297
~~Still a draft, only failing tests for now.~~
=> javascript tests and fixes for string.reverse() / string.slice() / string.to_graphemes()

CHANGELOG.md, src/gleam/string.gleam, src/gleam_stdlib.erl, test/gleam/string_test.gleam
- Fixes: https://github.com/gleam-lang/stdlib/issues/281
- Replaces: https://github.com/gleam-lang/stdlib/pull/295
=> add string.inspect()

src/gleam_stdlib.mjs
Ref: https://github.com/gleam-lang/stdlib/pull/298#issuecomment-1129833610
=> remove unused function

src/gleam/bit_builder.gleam, src/gleam/string_builder.gleam, test/gleam/bit_builder_test.gleam
=> fix: bit_builder.from_string_builder should wrap input

CHANGELOG.md, src/gleam/list.gleam, test/gleam/list_test.gleam
Attempts to fix https://github.com/gleam-lang/stdlib/issues/321
=> List.{all, any, contains} - Make recursion tail call optimization compatible

CHANGELOG.md, src/gleam/iterator.gleam, src/gleam/list.gleam, test/gleam/iterator_test.gleam, test/gleam/list_test.gleam
addresses #329 as well as ensures the range is fully inclusive
=> inclusive list.range and iterator.range

src/gleam/string.gleam, test/gleam/list_test.gleam, test/gleam/string_test.gleam
Should fix https://github.com/gleam-lang/stdlib/issues/335.
~The~ *Erlang* tests run a bit slow.
=> attempt to fix string slice tco

test/gleam/bool_test.gleam, test/gleam/list_test.gleam, test/gleam/regex_test.gleam, test/gleam/string_test.gleam
Fixes https://github.com/gleam-lang/stdlib/issues/337#issuecomment-1246373639
=> use should.be_true()/.be_false() instead of should.equal()

CHANGELOG.md, src/gleam/int.gleam, src/gleam/map.gleam, test/gleam/int_test.gleam
Closes https://github.com/gleam-lang/stdlib/issues/343
=> add `int.floor_divide`

CHANGELOG.md, src/gleam_stdlib.erl, test/gleam/regex_test.gleam
Closes https://github.com/gleam-lang/stdlib/issues/349
=> Bugfix regex.scan

CHANGELOG.md, src/gleam/list.gleam, test/gleam/list_test.gleam
Closes https://github.com/gleam-lang/stdlib/issues/352
=> add list.shuffle

src/gleam/string.gleam, src/gleam/uri.gleam
Improves links in hexdocs for:
* gleam/string
* gleam/uri
=> API docs: improve links

src/gleam/int.gleam, src/gleam/map.gleam
@NicklasXYZ suggested this optimization https://github.com/gleam-lang/stdlib/pull/344#issuecomment-1273689692
=> improve `int.floor_divide`

src/gleam/function.gleam
Thanks to @hayleigh-dot-dev and @tynanbe for a more specific and precise wording (than mine) on what currying is.
=> improve function.curry2 ... function.curry6 docblocks

CHANGELOG.md, src/gleam/io.gleam, src/gleam_stdlib.erl, src/gleam_stdlib.mjs
Sometimes you just wanna print to stderr, y'know? :)
=> add error variants to gleam/io for printing to stderr

CHANGELOG.md, src/gleam/list.gleam, test/gleam/list_test.gleam
Makes more sense. As discussed on Discord.
=> Make list.at return an error given sub-zero index

CHANGELOG.md, src/gleam/dynamic.gleam, test/gleam/dynamic_test.gleam
discussion conclusion here https://discord.com/channels/768594524158427167/1057603251119345734/1058045487825035335
=> Add Decode1 function

CHANGELOG.md, src/gleam_stdlib.mjs, test/gleam/dynamic_test.gleam
=> Object decode in Javascript ffi

test/eunit_progress.erl
On `main` against gleam nightly I do not have any erlang compiler warnings, but with this backport/PR applied I get:
```
build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@list_test.erl:343:21: Warning: no clause will ever match
%  343|                     true = case false of
%     |                     ^
build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@list_test.erl:380:21: Warning: no clause will ever match
%  380|                     true = case false of
%     |                     ^
```
Related to this test case:
https://github.com/gleam-lang/stdlib/blob/e6d553af85c42681fe948f2fad5a326cdc0701ce/test/gleam/list_test.gleam#L417-L427
=> backport eunit_progress from gleeunit

bin/test.sh
It seems this file is outdated and does not run anymore and isn't used anymore?
=> remove old shell script

CHANGELOG.md, src/gleam/list.gleam, src/gleam/map.gleam, src/gleam/option.gleam, test/gleam/list_test.gleam, test/gleam/option_test.gleam
Takes a list and groups the values by a key which is built from a key_selector function. Similar to `iterator.group`.
=> implements the list group function

CHANGELOG.md, src/gleam/float.gleam, src/gleam/int.gleam, test/gleam/float_test.gleam, test/gleam/int_test.gleam
If this ticket is desired: https://github.com/gleam-lang/gleam/issues/1984
... _then_ this PR should do it.
=> product-of-empty-list-of-numbers-could-return-1

CHANGELOG.md, src/gleam/regex.gleam, src/gleam_stdlib.erl, src/gleam_stdlib.mjs, test/gleam/regex_test.gleam
=> make `regex.scan`'s behavior consistent across targets

src/gleam/iterator.gleam, test/gleam/iterator_test.gleam
=> Make iterator.any/all TCO eligible in JavaScript

CHANGELOG.md, src/gleam/dynamic.gleam, src/gleam/iterator.gleam, src/gleam/result.gleam, src/gleam/uri.gleam, test/gleam/result_test.gleam
Closes https://github.com/gleam-lang/stdlib/issues/439
=> Deprecate result.then in favour of result.try

CHANGELOG.md, src/gleam/list.gleam, test/gleam/list_test.gleam
Add a `list.try_each` with its documentation and tests.
Closes #438
=> `list.try_each`

CHANGELOG.md, src/gleam/result.gleam, test/gleam/result_test.gleam
Leah suggested on Discord that the `result` module could make use of a `recover` function. I think it's a really good idea so here it is!
=> Add `result.try_recover`

CHANGELOG.md, src/gleam/order.gleam, test/gleam/order_test.gleam
Takes an ordering function, and returns the inverse of that function! Useful for sorting things in descending order
=> `order.reverse`

CHANGELOG.md
Almost everything was already broken at line length of 80, just some wasn't.
=> break at line 80

CHANGELOG.md, src/gleam/iterator.gleam, test/gleam/iterator_test.gleam
A new function that imitates the `yield` keyword found in many languages.
=> iterator.yield

src/gleam/dynamic.gleam
~~also `gleam format` really wanted to tweak some things~~
I just had a slightly old version oops
=> docs: fix `tuple6` example

CHANGELOG.md, src/gleam/bool.gleam, test/gleam/bool_test.gleam
Here's an [example use case](https://github.com/tynanbe/argamak/blob/934e06660b04f7bdfc20bb845bb9ae420cd688a7/src/argamak/tensor.gleam#L3806,L3881).
=> Add bool.lazy_guard

src/gleam/dynamic.gleam
I assume this is the intention.
=> Use optional_field in optional_field docs

src/gleam/dict.gleam, src/gleam/dynamic.gleam, src/gleam/function.gleam, src/gleam/iterator.gleam, src/gleam/list.gleam, src/gleam/pair.gleam, src/gleam/result.gleam, src/gleam/string.gleam
I noticed some trailing whitespace in the repo, so I ran [lineman](https://github.com/josephtlyons/lineman) across it.
=> Remove trailing whitespace

CHANGELOG.md, src/gleam/order.gleam, test/gleam/order_test.gleam
=> Add `order.break_tie` and `order.lazy_break_tie`

src/gleam/int.gleam
=> Edit example

src/gleam/dict.gleam
Addresses https://github.com/gleam-lang/stdlib/issues/575
=> Update examples for `dict.to_list`

CHANGELOG.md, src/gleam/dict.gleam, test/gleam/dict_test.gleam
See https://github.com/gleam-lang/stdlib/pull/588
=> Add `dict.each`

CHANGELOG.md, src/gleam/set.gleam, test/gleam/set_test.gleam
Add `symmetric_difference` to set module. Closes #594.
=> Add `set.symmetric_difference`

CHANGELOG.md, src/gleam/dict.gleam, test/gleam/dict_test.gleam
=> Add `dict.combine` function

CHANGELOG.md, src/gleam/dict.gleam, src/gleam/set.gleam, test/gleam/dict_test.gleam, test/gleam/set_test.gleam
Added a similar to `list.is_empty` functions to dict and set.
=> Add dict.is_empty and set.is_empty

src/gleam/list.gleam
Came across this when starting out with Gleam.
=> Fix word in list module description

src/gleam/iterator.gleam
=> Fix iterator.find_map example

CHANGELOG.md, src/gleam/regex.gleam, src/gleam_stdlib.erl, src/gleam_stdlib.mjs, test/gleam/regex_test.gleam
Add a replace function to the regex package. If accepted, this should resolve issue #621
=> Implement regex.replace

src/gleam/regex.gleam
=> Fix gleam/regex replace examples OK casing

src/gleam/bool.gleam, src/gleam/float.gleam, src/gleam/int.gleam, src/gleam/iterator.gleam, src/gleam/list.gleam, src/gleam/regex.gleam, src/gleam/set.gleam
Small typo fixes to the examples that I found by running my doctest tool :3
=> Fix typos in examples

CHANGELOG.md, src/gleam/dynamic.gleam, src/gleam/list.gleam, test/gleam/iterator_test.gleam
=> Deprecate `list.concat`

.vscode/extensions.json, .vscode/settings.json
I added some formatter settings for better development environment.
=> add formatter configurations

src/gleam/dict.gleam, src/gleam/dynamic.gleam, src/gleam/iterator.gleam, src/gleam/list.gleam, src/gleam/queue.gleam, src/gleam/result.gleam, src/gleam/set.gleam, src/gleam/uri.gleam
- I noticed I missed a couple of looping functions so I changed those as well.
- As @inoas pointed out there were a couple of places left where the helper function was above the function using it. I changed those to make sure the codebase has a consistent style
- There was a place where we still used `map` instead of `dict` so I changed it
=> Missing loops!

.github/workflows/ci.yml, test/gleam/string_test.gleam
=> Remove regex dependency from test module

CHANGELOG.md, src/gleam/string.gleam
Benchmarks:
```
Input               Function                       IPS           Min           P99
line1               old                    354760.1315        0.0023        0.0045
line1               new                   1810683.7406        0.0002        0.0024
line10              old                    300981.0341        0.0023        0.0065
line10              new                    384372.9958        0.0011        0.0057
human rights 1      old                      3558.5401        0.2745        0.3157
human rights 1      new                   1612774.2418        0.0002        0.0022
human rights 10     old                      3522.1855        0.2751        0.3244
human rights 10     new                    382014.5499        0.0011        0.0079
human rights 100    old …
```
=> Optimise `drop_start`

src/gleam/dynamic/decode.gleam
Hi! 👋  I believe there's a typo in the documentation.
=> Fix a typo in the documentation

CHANGELOG.md, gleam.toml
Fixes https://github.com/gleam-lang/stdlib/issues/804
=> Add recent 0.54 release to changelog

src/gleam_stdlib.mjs, src/gleam_stdlib_decode_ffi.mjs, test/gleam_stdlib_test_ffi.mjs, test/gleeunit.mjs
- Removed some unused imports
- Made some read-only variables `const`
=> Minor improvements to .mjs code

CHANGELOG.md, src/gleam/uri.gleam, src/gleam_stdlib.erl, test/gleam/uri_test.gleam
This PR closes #855, I've also made sure the behaviour is consistent across targets!
=> Make sure empty port is parsed correctly on both targets
